services:

  hackathon-auth-service:
    build: ./Hackathon.AuthService
    container_name: hackathon-auth-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - mednet

  hackathon-user-service:
    build: ./Hackathon.UserService
    container_name: hackathon-user-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - mednet

  hackathon-schedule-service:
    build: ./Hackathon.ScheduleService
    container_name: hackathon-schedule-service
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - mednet

  hackathon-consultation-service:
    build: ./Hackathon.ConsultationService
    container_name: hackathon-consultation-service
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - mednet

networks:
  mednet:
    name: hackatonfiap5nett_mednet
    driver: bridge