name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: docker build -t ghcr.io/ghonda/hackathon-auth:latest .
        docker push ghcr.io/ghonda/hackathon-auth:latest

    - name: Set up Kubernetes
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        version: 1.21.0

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/authservice.yaml
