apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultation-deployment
  labels:
    app: consultation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultation
  template:
    metadata:
      labels:
        app: consultation
    spec:
      containers:
        - name: consultation
          image: ghcr.io/${{ github.repository_owner }}/hackathon-consultation:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: consultation-service
spec:
  selector:
    app: consultation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
