apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-deployment
  labels:
    app: schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - name: schedule
          image: ghcr.io/ghonda/hackathon-schedule:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: schedule-service
spec:
  selector:
    app: schedule
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
