name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/ghonda/hackathon-auth # Seu usuário/nome da imagem
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }} # Nome do seu cluster AKS
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }} # Nome do RG do seu cluster AKS
  KUBERNETES_MANIFESTS_PATH: "HackatonFiap5NETT/k8s" # Caminho para seus manifestos

jobs:
  build-and-push-image:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Hackathon.AuthService # Caminho para o diretório que contém o Dockerfile
          file: ./Hackathon.AuthService/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          # github.sha garante uma tag única por commit

  deploy-to-aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build-and-push-image # Garante que este job só roda após o build e push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          action: "deploy"
          manifests: |
            ${{ env.KUBERNETES_MANIFESTS_PATH }}/authservice.yaml
          images: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
